name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, converted_to_draft]

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    secrets: inherit
