name: Release

on: workflow_dispatch

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  unit_tests:
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
      attestations: write
    needs: [checks]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}'
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      # - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
      #   run: npm audit signatures

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: npx semantic-release

      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: '${{ github.workspace }}/src'

  update_docs:
    needs: [release]
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
